# ============================================================
#  Lametna - build a shareable release APK (Windows / PowerShell)
#
#  NOTE: this file is intentionally ASCII-only. Windows PowerShell 5.1
#  reads .ps1 files as ANSI, so non-ASCII text (Arabic, arrows) breaks
#  the parser. Keep it ASCII.
#
#  Usage from the project root:
#     powershell -ExecutionPolicy Bypass -File tool\build_apk.ps1
#
#  Options:
#     -Split   build one APK per ABI (smaller, for advanced users)
#     -Clean   clean the previous build first
# ============================================================
param(
    [switch]$Split,
    [switch]$Clean
)

$ErrorActionPreference = "Stop"
Set-Location (Split-Path $PSScriptRoot -Parent)

Write-Host ""
Write-Host "==== Lametna - release build ====" -ForegroundColor Cyan
Write-Host ""

# ---- 1) env.json ------------------------------------------------
if (-not (Test-Path "env.json")) {
    Write-Host "[X] env.json not found in the project root." -ForegroundColor Red
    Write-Host "    Create it with your Supabase values (Settings -> API):" -ForegroundColor Yellow
    Write-Host '    {'
    Write-Host '      "SUPABASE_URL": "https://YOUR-REF.supabase.co",'
    Write-Host '      "SUPABASE_ANON_KEY": "YOUR_PUBLIC_ANON_KEY",'
    Write-Host '      "APP_ENV": "prod"'
    Write-Host '    }'
    exit 1
}
Write-Host "[OK] env.json found" -ForegroundColor Green

# ---- 2) signing key ---------------------------------------------
if (Test-Path "android\key.properties") {
    Write-Host "[OK] release signing key found (android\key.properties)" -ForegroundColor Green
} else {
    Write-Host "[!] android\key.properties missing - the build will be signed with the DEBUG key." -ForegroundColor Yellow
    Write-Host "    Fine for testing, but do not distribute it: future updates will not install over it." -ForegroundColor Yellow
    Write-Host "    See docs/SHARE_APK.md" -ForegroundColor Yellow
}
Write-Host ""

# ---- helpers -----------------------------------------------------
function Remove-StalePluginFiles {
    # The Android plugin registrant is generated by "flutter pub get".
    # A stale copy made during a debug/test run keeps referencing
    # integration_test, which does not exist in release builds.
    $paths = @(
        "android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java",
        ".flutter-plugins",
        ".flutter-plugins-dependencies"
    )
    foreach ($p in $paths) {
        if (Test-Path $p) { Remove-Item -Force $p -ErrorAction SilentlyContinue }
    }
}

function Invoke-Build([string]$logFile) {
    $buildArgs = @("build", "apk", "--release", "--dart-define-from-file=env.json")
    if ($Split) { $buildArgs += "--split-per-abi" }
    Write-Host "==> flutter $($buildArgs -join ' ')" -ForegroundColor Cyan
    Write-Host "    (the first build can take 5-15 minutes)" -ForegroundColor DarkGray
    & flutter @buildArgs 2>&1 | Tee-Object -FilePath $logFile
    return $LASTEXITCODE
}

# ---- 3) build ----------------------------------------------------
if ($Clean) {
    Write-Host "==> flutter clean" -ForegroundColor Cyan
    flutter clean
}

Remove-StalePluginFiles

Write-Host "==> flutter pub get" -ForegroundColor Cyan
flutter pub get
if ($LASTEXITCODE -ne 0) { Write-Host "[X] pub get failed." -ForegroundColor Red; exit $LASTEXITCODE }

$log = Join-Path $env:TEMP "lametna_build.log"
$code = Invoke-Build $log

# ---- 3b) known Flutter bug: integration_test in a release build ---
# Some Flutter versions write integration_test (a dev dependency) into
# GeneratedPluginRegistrant.java while Gradle correctly leaves its AAR
# out of release builds -> "package dev.flutter.plugins.integration_test
# does not exist". Workaround: build once without that dev dependency,
# then put pubspec.yaml back exactly as it was.
if ($code -ne 0 -and (Select-String -Path $log -Pattern "dev.flutter.plugins.integration_test" -Quiet)) {
    Write-Host ""
    Write-Host "[!] Known Flutter issue: integration_test leaked into the release build." -ForegroundColor Yellow
    Write-Host "    Retrying with integration_test temporarily disabled..." -ForegroundColor Yellow
    Write-Host ""

    $backup = "pubspec.yaml.buildbak"
    Copy-Item "pubspec.yaml" $backup -Force
    try {
        $lines = Get-Content "pubspec.yaml"
        $out = New-Object System.Collections.Generic.List[string]
        for ($i = 0; $i -lt $lines.Count; $i++) {
            if ($lines[$i] -match '^\s{2}integration_test:\s*$') {
                $out.Add("# [build_apk.ps1] temporarily disabled")
                $out.Add("#" + $lines[$i])
                if ($i + 1 -lt $lines.Count -and $lines[$i + 1] -match '^\s+sdk:\s*flutter\s*$') {
                    $out.Add("#" + $lines[$i + 1]); $i++
                }
            } else {
                $out.Add($lines[$i])
            }
        }
        $utf8NoBom = New-Object System.Text.UTF8Encoding $false
        [System.IO.File]::WriteAllLines((Resolve-Path "pubspec.yaml").Path, $out, $utf8NoBom)

        Remove-StalePluginFiles
        flutter pub get | Out-Null
        $code = Invoke-Build $log
    }
    finally {
        Copy-Item $backup "pubspec.yaml" -Force
        Remove-Item $backup -Force -ErrorAction SilentlyContinue
        flutter pub get | Out-Null
        Write-Host "[OK] pubspec.yaml restored (integration_test is back)." -ForegroundColor Green
    }
}

if ($code -ne 0) { Write-Host "[X] build failed. See the log above." -ForegroundColor Red; exit $code }

# ---- 4) result ---------------------------------------------------
Write-Host ""
Write-Host "[DONE] APK files ready to share:" -ForegroundColor Green
Get-ChildItem "build\app\outputs\flutter-apk\*.apk" |
    Where-Object { $_.Name -notlike "*debug*" } |
    ForEach-Object {
        $mb = [math]::Round($_.Length / 1MB, 1)
        Write-Host ("   " + $_.FullName + "   (" + $mb + " MB)")
    }
Write-Host ""
Write-Host "Send app-release.apk as a DOCUMENT (WhatsApp / Telegram / download link)." -ForegroundColor Cyan
Write-Host "On the receiving phone: open the file -> allow install from this source -> Install." -ForegroundColor Cyan
Write-Host ""
