[build]
  publish = "."

[[redirects]]
  from = "/r/*"
  to = "/r/index.html"
  status = 200

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"
