/// English strings — secondary language (LTR).
const Map<String, String> enStrings = <String, String>{
  'app_name': 'Lametna',
  'slogan': 'Lametna brings us together… the game starts here',

  'ok': 'OK', 'cancel': 'Cancel', 'save': 'Save', 'close': 'Close',
  'retry': 'Retry', 'next': 'Next', 'back': 'Back', 'done': 'Done',
  'confirm': 'Confirm', 'delete': 'Delete', 'search': 'Search', 'loading': 'Loading…',
  'copy': 'Copy', 'copied': 'Copied', 'share': 'Share', 'refresh': 'Refresh',
  'yes': 'Yes', 'no': 'No', 'optional': 'Optional', 'skip': 'Skip',
  'points': 'pts', 'level': 'Level', 'you': 'You',

  'choose_language': 'Choose your language',
  'language': 'Language',
  'arabic': 'العربية',
  'english': 'English',
  'welcome_title': 'Welcome to Lametna',
  'welcome_body': 'Text-based party games with friends and family, from Yemen and all over the world.\n'
      'No camera, no microphone, no calls.',
  'get_started': 'Get started',

  'sign_in': 'Sign in',
  'sign_up': 'Create account',
  'sign_out': 'Sign out',
  'guest_mode': 'Play as guest',
  'guest_note': 'Play instantly with no email: join any room with a code. '
      'Creating your own room and keeping your points needs a full account later.',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Confirm password',
  'forgot_password': 'Forgot password?',
  'reset_password': 'Reset password',
  'reset_sent': 'We sent a reset link to your email.',
  'no_account': "Don't have an account?",
  'have_account': 'Already have an account?',
  'sign_out_confirm': 'Sign out of your account?',
  'invalid_email': 'Enter a valid email address',
  'weak_password': 'Password must be at least 8 characters',
  'password_mismatch': 'Passwords do not match',
  'signup_success': 'Account created successfully',

  'profile': 'Profile',
  'setup_profile': 'Set up your profile',
  'nickname': 'Nickname',
  'nickname_hint': 'e.g. Abu Ali',
  'nickname_too_short': 'Nickname is too short',
  'nickname_taken': 'That nickname is taken, try another',
  'choose_avatar': 'Choose an avatar',
  'country': 'Country',
  'country_optional': 'Country (optional)',
  'show_country': 'Show my country to players',
  'stats': 'Stats',
  'games_played': 'Matches',
  'games_won': 'Wins',
  'total_points': 'Total points',
  'badges': 'Badges',
  'no_badges': 'No badges yet — play to earn your first one!',
  'member_since': 'Member since',
  'profile_saved': 'Profile saved',

  'home': 'Home',
  'games': 'Games',
  'create_room': 'Create room',
  'join_by_code': 'Join with code',
  'public_rooms': 'Public rooms',
  'leaderboard': 'Leaderboard',
  'settings': 'Settings',
  'quick_play': 'Quick play',
  'welcome_back': 'Hi',

  'cat_yemeni': 'Yemeni', 'cat_arabic': 'Arabic', 'cat_global': 'Global',
  'cat_family': 'Family', 'cat_fast': 'Fast', 'cat_competitive': 'Competitive',
  'all_games': 'All games',
  'players_range': 'Players',
  'round_time': 'Round time',
  'rounds': 'Rounds',
  'seconds': 's',

  'room': 'Room',
  'room_code': 'Room code',
  'enter_code': 'Enter room code',
  'code_hint': 'e.g. ABC123',
  'room_title': 'Room name',
  'room_public': 'Public room',
  'room_private': 'Private room',
  'room_password': 'Room password',
  'room_password_hint': 'Leave empty for no password',
  'max_players': 'Max players',
  'join': 'Join',
  'join_as_spectator': 'Join as spectator',
  'game_in_progress_hint': 'A match is already running. You can join as a spectator and watch.',
  'leave_room': 'Leave room',
  'leave_confirm': 'Leave this room?',
  'waiting_room': 'Waiting room',
  'players': 'Players',
  'spectators': 'Spectators',
  'host': 'Host',
  'ready': 'Ready',
  'not_ready': 'Not ready',
  'im_ready': "I'm ready",
  'cancel_ready': 'Cancel ready',
  'start_game': 'Start match',
  'waiting_for_host': 'Waiting for the host to start…',
  'waiting_for_players': 'Waiting for players to join…',
  'no_public_rooms': 'No public rooms right now — create yours!',
  'room_created': 'Room created',
  'share_code_hint': 'Share this code with your friends',
  'transfer_host': 'Transfer host',
  'kick_player': 'Kick player',
  'ban_player': 'Ban from room',
  'mute_player': 'Mute',
  'unmute_player': 'Unmute',
  'play_again': 'Play again',
  'abort_game': 'Stop match',

  'chat': 'Chat',
  'message_hint': 'Write a message…',
  'send': 'Send',
  'chat_rules': 'Text chat only. Be respectful.',

  'round': 'Round',
  'time_left': 'Time left',
  'submit': 'Submit',
  'submitted': 'Submitted ✓',
  'waiting_others': 'Waiting for other players…',
  'results': 'Results',
  'round_results': 'Round results',
  'final_results': 'Final results',
  'match_over': 'Match over',
  'winner': 'Winner',
  'winners': 'Winners',
  'scoreboard': 'Scoreboard',
  'vote': 'Vote',
  'vote_now': 'Vote now',
  'your_vote': 'Your vote',
  'correct_answer': 'Correct answer',
  'correct': 'Correct', 'wrong': 'Wrong',

  'apo_letter': 'Letter',
  'apo_instructions': 'Write a word starting with the letter for every category before time runs out.',
  'cat_name': 'Name', 'cat_animal': 'Animal', 'cat_plant': 'Plant',
  'cat_object': 'Object', 'cat_country': 'Country', 'cat_city': 'City',
  'cat_food': 'Food', 'cat_job': 'Job', 'cat_yemeni_city': 'Yemeni city',
  'cat_yemeni_name': 'Yemeni name', 'cat_home_item': 'Item at home',

  'mafia': 'Mafia',
  'your_role': 'Your role',
  'role_mafia': 'Mafia', 'role_citizen': 'Citizen', 'role_doctor': 'Doctor',
  'role_detective': 'Detective', 'role_guard': 'Guard',
  'role_mafia_desc': 'Eliminate a citizen each night without being caught.',
  'role_citizen_desc': 'Discuss and vote to uncover the mafia.',
  'role_doctor_desc': 'Save one player each night.',
  'role_detective_desc': 'Investigate one player each night.',
  'role_guard_desc': 'Protect a player from being killed tonight.',
  'night_phase': 'Night',
  'day_phase': 'Day',
  'night_hint': 'The town is asleep… make your move in secret.',
  'day_hint': 'Discuss, then vote for your suspect.',
  'choose_target': 'Choose a target',
  'action_sent': 'Your action was sent secretly',
  'investigation_result': 'Investigation result',
  'is_mafia': 'This player IS mafia!',
  'is_not_mafia': 'This player is not mafia.',
  'killed_tonight': 'Killed tonight',
  'nobody_died': 'Nobody died tonight',
  'saved_by_doctor': 'Saved by the doctor!',
  'lynched': 'Voted out',
  'no_lynch': 'The vote was tied — nobody was eliminated',
  'mafia_wins': 'Mafia wins!',
  'citizens_wins': 'Citizens win!',
  'you_are_dead': 'You are out — you can only watch now',
  'mafia_chat': 'Mafia chat',
  'mafia_partners': 'Your partners',

  'who_am_i': 'Who am I?',
  'who_am_i_hint': 'Ask yes/no questions, then guess the character.',
  'guess_hint': 'Type your guess',
  'true_false': 'True or False',
  'answer_true': 'True', 'answer_false': 'False',
  'guess_word': 'Guess the word',
  'hint_number': 'Hint',
  'liar': 'The Liar',
  'liar_your_word': 'Your word',
  'liar_describe': 'Describe your word without saying it',
  'liar_vote': 'Who is the liar?',
  'liar_was': 'The liar was',
  'liar_caught': 'The liar was caught!',
  'liar_escaped': 'The liar escaped!',
  'proverbs': 'Finish the proverb',
  'proverbs_hint': 'Complete the proverb — several variants are accepted.',
  'group_story': 'Group story',
  'story_write': 'Add a sentence to the story',
  'story_vote': 'Vote for the best sentence',
  'best_line': 'Best sentence',

  'scope_global': 'Global', 'scope_arab': 'Arab', 'scope_yemen': 'Yemen',
  'period_week': 'Weekly', 'period_month': 'Monthly', 'period_all': 'All time',
  'your_rank': 'Your rank',
  'no_leaderboard': 'No results for this period yet.',

  'appearance': 'Appearance',
  'dark_mode': 'Dark mode',
  'theme_system': 'System', 'theme_light': 'Light', 'theme_dark': 'Dark',
  'notifications': 'Notifications',
  'privacy': 'Privacy',
  'privacy_policy': 'Privacy policy',
  'terms': 'Terms of use',
  'rules': 'Community rules',
  'support': 'Contact support',
  'report_problem': 'Report a problem',
  'delete_account': 'Delete account',
  'delete_account_warning': 'Your name and messages will be hidden permanently. This cannot be undone.',
  'about': 'About',
  'version': 'Version',

  'report': 'Report',
  'report_user': 'Report a player',
  'report_reason': 'Reason',
  'report_details': 'More details (optional)',
  'report_sent': 'Report submitted, thank you.',
  'block_user': 'Block this player',
  'unblock_user': 'Unblock',
  'blocked': 'Blocked',
  'reason_abuse': 'Abuse',
  'reason_racism': 'Racism',
  'reason_sectarian': 'Sectarianism',
  'reason_bullying': 'Bullying',
  'reason_incitement': 'Incitement',
  'reason_profanity': 'Profanity',
  'reason_doxxing': 'Sharing personal data',
  'reason_impersonation': 'Impersonation',
  'reason_spam': 'Spam',
  'reason_other': 'Other',

  'no_internet': 'No internet connection',
  'no_internet_body': 'Check your network — we will reconnect automatically.',
  'disconnected': 'Disconnected',
  'reconnecting': 'Reconnecting…',
  'reconnected': 'Reconnected',
  'error_title': 'Something went wrong',
  'error_body': 'Sorry, an unexpected error occurred.',
  'not_found': 'Page not found',
  'config_missing': 'Server configuration missing',
  'empty': 'Nothing here yet',

  // --- New games (migration 0012) ---
  'capitals': 'Capitals',
  'capitals_hint': 'Pick the right capital.',
  'flags': 'Flags',
  'flags_hint': 'Look at the flag and pick the country.',
  'riddles': 'Riddles',
  'riddles_hint': 'Type your answer — hints appear gradually.',
  'islamic': 'Islamic Quiz',
  'islamic_hint': 'Pick the right answer.',
  'sports': 'Sports',
  'sports_hint': 'Pick the right answer.',
  'history': 'History',
  'history_hint': 'Pick the right answer.',
  'emoji_puzzle': 'Emoji Puzzle',
  'emoji_puzzle_hint': 'Guess what the emojis mean.',
  'fast_math': 'Fast Math',
  'fast_math_hint': 'Type the result in digits — fastest wins.',
  'secret_job': 'Secret Job',
  'best_answer': 'Best Answer',

  // --- Party games (migration 0013) ---
  'wink': 'Wink Murder',
  'spy': 'The Spy',
  'you_are_the_spy': 'You are the spy! 🕵️‍♀️',
  'confessions': 'Whose Confession?',
  'confessions_write': 'Write your secret confession',
  'confessions_guess': 'Whose confession is this?',
  'confessions_author': 'The confession belongs to',
  'most_likely': 'Most Likely To',
  'never_have_i': 'Never Have I Ever',
  'never_have_i_hint': 'Be honest.',
  'would_you_rather': 'Would You Rather',
  'would_you_rather_hint': 'Pick one of the two.',
  'truth': 'Truth Seat',
  'truth_your_turn': 'Your turn in the truth seat',
  'truth_answer_hint': 'Answer honestly',
  'truth_waiting': 'Waiting for their answer…',
  'truth_waiting_rate': 'Waiting for the others to rate…',
  'truth_rate': 'Rate the answer',
  'truth_like': 'Liked it',
  'truth_dislike': 'Did not like it',
  'truth_likes': 'Likes',

  // ── Legal consent before sign-up ──
  'legal_read_first': 'Before you start, please read:',
  'legal_consent':
      'By continuing you agree to the Terms of Use, the Privacy Policy and the community rules.',

  // ── Invite friends ──
  'invite_friends': 'Invite friends',
  'invite_title': 'Invite your friends',
  'invite_how':
      'Send the link to your friends - one tap opens the app and joins the room.',
  'share_invite': 'Share link',
  'copy_link': 'Copy link',
  'invite_link_line': 'Tap to join instantly:\n{url}',
  'copy_invite': 'Copy invite message',
  'copy_code': 'Copy code only',
  'invite_copied': 'Invite copied - paste it in your chat',
  'invite_message':
      'Come play Lametna! 🎲\nRoom code: {code}',
  'invite_download': 'Get the app here: {url}',

  // ── Support ──
  'contact_support': 'Contact support',
  'support_how': 'Email us at the address below and we will reply shortly.',
  'open_mail_app': 'Open mail app',
  'copy_email': 'Copy email',
  'email_copied': 'Email copied',
  'support_copied': 'Email and message copied - paste them in your mail app',
  'support_subject_help': 'Lametna - question / help request',
  'support_subject_bug': 'Lametna - bug report',
  'support_body_hint': 'Write your message here in detail:',

  // ── Guest & account upgrade ──
  'guest_badge': 'Guest',
  'guest_limited_title': 'Creating rooms needs a full account',
  'guest_limited_body': 'As a guest you can join any room with a code and play '
      'right away. To create your own room, add an email and a password - you '
      'keep your points and your name, nothing is lost.',
  'upgrade_title': 'Complete your account',
  'upgrade_body':
      'Add an email and a password to your current account. Your points and history stay exactly as they are.',
  'upgrade_cta': 'Complete sign-up',
  'upgrade_done': 'Your account is ready 🎉',
  'later': 'Later',
  'benefit_create_rooms': 'Create your own rooms and invite anyone',
  'benefit_leaderboard': 'Keep your points and appear on the leaderboard',
  'benefit_restore': 'Recover your account on a new phone or after reinstalling',
  'benefit_devices': 'Sign in from any device with the same account',
};
